// <auto-generated />
using System;
using Demo_ASPMVC_02.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo_ASPMVC_02.DAL.Migrations
{
    [DbContext(typeof(PokedexContext))]
    [Migration("20240917134126_initDb")]
    partial class initDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo_ASPMVC_02.DAL.Entities.Pokemon", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numero"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PreEvolutionNumero")
                        .HasColumnType("int");

                    b.Property<int>("Type1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Type2Id")
                        .HasColumnType("int");

                    b.Property<int>("Vie")
                        .HasColumnType("int");

                    b.HasKey("Numero")
                        .HasName("PK_Pokemon");

                    b.HasIndex("PreEvolutionNumero")
                        .IsUnique()
                        .HasFilter("[PreEvolutionNumero] IS NOT NULL");

                    b.HasIndex("Type1Id");

                    b.HasIndex("Type2Id");

                    b.ToTable("Pokemon", (string)null);

                    b.HasData(
                        new
                        {
                            Numero = 1,
                            Nom = "Bulbizarre",
                            Type1Id = 1,
                            Vie = 100
                        },
                        new
                        {
                            Numero = 2,
                            Nom = "Herbizarre",
                            PreEvolutionNumero = 1,
                            Type1Id = 1,
                            Vie = 150
                        },
                        new
                        {
                            Numero = 3,
                            Nom = "Florizarre",
                            PreEvolutionNumero = 2,
                            Type1Id = 1,
                            Vie = 200
                        },
                        new
                        {
                            Numero = 4,
                            Nom = "Carapuce",
                            Type1Id = 2,
                            Vie = 100
                        });
                });

            modelBuilder.Entity("Demo_ASPMVC_02.DAL.Entities.PokemonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_PokemonType");

                    b.ToTable("PokemonType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Plante"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Eau"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Feu"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Roche"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Normal"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Psy"
                        });
                });

            modelBuilder.Entity("Demo_ASPMVC_02.DAL.Entities.Pokemon", b =>
                {
                    b.HasOne("Demo_ASPMVC_02.DAL.Entities.Pokemon", "PreEvolution")
                        .WithOne()
                        .HasForeignKey("Demo_ASPMVC_02.DAL.Entities.Pokemon", "PreEvolutionNumero");

                    b.HasOne("Demo_ASPMVC_02.DAL.Entities.PokemonType", "Type1")
                        .WithMany()
                        .HasForeignKey("Type1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo_ASPMVC_02.DAL.Entities.PokemonType", "Type2")
                        .WithMany()
                        .HasForeignKey("Type2Id");

                    b.Navigation("PreEvolution");

                    b.Navigation("Type1");

                    b.Navigation("Type2");
                });
#pragma warning restore 612, 618
        }
    }
}
